name: Visionsbloggen
favicon: null
layout_spectrum: 0
typography_spectrum: 0.45039
title: Visionsbloggen
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#16171b'
    - '#92d6ff'
    - '#e86e23'
    - '#cc252d'
    - '#f5c74d'
  brandStrength: 0.1875
  lightness: 0.5
  saturation: 0.25
  rhythmicContrast: 0.75
purpose: []
