name: Visionsbloggen
favicon: null
layout_spectrum: 0.29432915756478906
typography_spectrum: 0.5109270408283919
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#303026'
    - '#91948d'
    - '#289dff'
    - '#a4c8ff'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 0.25
  rhythmicContrast: 0.75
purpose: []
